
package com.mmarques.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSOAPClienteComAutenticacaoUsuarioSenha", targetNamespace = "http://controller.mmarques.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSOAPClienteComAutenticacaoUsuarioSenha {


    /**
     * 
     * @return
     *     returns java.util.List<com.mmarques.ws.Cliente>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://controller.mmarques.com/", className = "com.mmarques.ws.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://controller.mmarques.com/", className = "com.mmarques.ws.ListarResponse")
    @Action(input = "http://controller.mmarques.com/WebServiceSOAPClienteComAutenticacaoUsuarioSenha/listarRequest", output = "http://controller.mmarques.com/WebServiceSOAPClienteComAutenticacaoUsuarioSenha/listarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://controller.mmarques.com/WebServiceSOAPClienteComAutenticacaoUsuarioSenha/listar/Fault/Exception")
    })
    public List<Cliente> listar()
        throws Exception_Exception
    ;

}
