
package com.mmarques.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSOAPEnviaRecebeArquivo", targetNamespace = "http://resource.mmarques.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSOAPEnviaRecebeArquivo {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://resource.mmarques.com/", className = "com.mmarques.ws.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://resource.mmarques.com/", className = "com.mmarques.ws.UploadResponse")
    @Action(input = "http://resource.mmarques.com/WebServiceSOAPEnviaRecebeArquivo/uploadRequest", output = "http://resource.mmarques.com/WebServiceSOAPEnviaRecebeArquivo/uploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://resource.mmarques.com/", className = "com.mmarques.ws.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://resource.mmarques.com/", className = "com.mmarques.ws.DownloadResponse")
    @Action(input = "http://resource.mmarques.com/WebServiceSOAPEnviaRecebeArquivo/downloadRequest", output = "http://resource.mmarques.com/WebServiceSOAPEnviaRecebeArquivo/downloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
